--- !ditz.rubyforge.org,2008-03-06/project 
name: xkcdroute
version: "0.3"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: xkcdroute
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: release 0.1
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-06-29 15:04:24.123391 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - initial release
